server:
  port: 8972

spring:
  application:
    name: msvc-venta
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1522/XEPDB1
    username: Userapp
    password: contraseña
  jpa:
    hibernate:
      ddl-auto: update
    database: oracle
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka