server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: msvc-usuario
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1/usuarios/**
        - id: msvc-producto
          uri: http://localhost:8003
          predicates:
            - Path=/api/v1/productos/**
        - id: msvc-venta
          uri: http://localhost:8972
          predicates:
            - Path=/api/v1/ventas/**
        - id: msvc-recordatorio
          uri: http://localhost:8005
          predicates:
            - Path=/api/v1/recordatorios/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
